Update scripts
 - Filter scripts output:
   - State script state
   - Log all other output for dedicated files
 - Build libraries instead of getting it from package manager
 - Modify script code structure to improve clarity
 - Other minor changes

diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -22,6 +22,10 @@ set -e
 PROJECT_ROOT_DIR="$(cd $(dirname "$0")/.. && pwd -P)"
 SCRIPTS_DIR="${PROJECT_ROOT_DIR}/script"
 
+SCRIPT_NAME=$(basename -- "$0")
+TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
+LOG_FILE="${PROJECT_ROOT_DIR}/${SCRIPT_NAME}_${TIMESTAMP}.log"
+
 build_punica () {
     cmake_arguments=""
 
@@ -29,19 +33,23 @@ build_punica () {
         cmake_arguments="${cmake_arguments} $1"
     fi
 
-    mkdir -p ${PROJECT_ROOT_DIR}/build/src
-    if ! [ $? -eq 0 ]; then
-        echo "Failed to create build directory!"
-        return 1
-    fi
+    {
+        mkdir -p ${PROJECT_ROOT_DIR}/build/src &&
+        eval "cd ${PROJECT_ROOT_DIR}/build" &&
+        eval "cmake ${cmake_arguments} ${PROJECT_ROOT_DIR}" &&
+        make &&
+        cd -
+    } >> ${LOG_FILE} 2>&1 || {
+        (>&2 echo "Failed to build punica!")
+        (>&2 echo "\nFor more information refer to ${LOG_FILE}")
 
-    eval "cd ${PROJECT_ROOT_DIR}/build"
-    eval "cmake ${cmake_arguments} ${PROJECT_ROOT_DIR}"
-    make
-    cd -
+        return 1
+    }
 }
 
 eval "${SCRIPTS_DIR}/bootstrap"
 
 echo "==> Building punica..."
 build_punica "$@"
+
+echo "Finished setting up punica!"
diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -22,13 +22,18 @@ set -e
 PROJECT_ROOT_DIR="$(cd $(dirname "$0")/.. && pwd -P)"
 SCRIPTS_DIR="${PROJECT_ROOT_DIR}/script"
 
+SCRIPT_NAME=$(basename -- "$0")
+TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
+LOG_FILE="${PROJECT_ROOT_DIR}/${SCRIPT_NAME}_${TIMESTAMP}.log"
+
+CERTIFICATE_SETTINGS_TEMPLATE="${PROJECT_ROOT_DIR}/certificate_template.cfg"
 TEST_PRIVATE_KEY="${PROJECT_ROOT_DIR}/private.key"
 TEST_CERTIFICATE="${PROJECT_ROOT_DIR}/certificate.pem"
 OTHER_TEST_PRIVATE_KEY="${PROJECT_ROOT_DIR}/other_private.key"
 OTHER_TEST_CERTIFICATE="${PROJECT_ROOT_DIR}/other_certificate.pem"
 
 generate_key_and_certificate () {
-    if [ "$#" -ne 2 ]; then
+    if [ "$#" -ne 3 ]; then
         echo "Illegal number of parameters"
         return 1
     fi
@@ -37,15 +42,25 @@ generate_key_and_certificate () {
         echo "Private key file name argument is missing or is invalid"
         return 1
     fi
-    
+
     if [ -z "$2" ]; then
         echo "Certificate file name argument is missing or is invalid"
         return 1
     fi
 
-    openssl genrsa -out $1 2048
+    if [ -z "$3" ]; then
+        echo "Certificate template file name argument is missing or is invalid"
+        return 1
+    fi
 
-    openssl req -days 365 -out $2 -new -x509 -key $1 -subj '/CN=localhost'
+    {
+        eval "certtool --generate-privkey --outfile $1" &&
+        certtool --generate-self-signed --load-privkey $1 --outfile $2 --template $3
+    } >> ${LOG_FILE} 2>&1 || {
+        (>&2 echo "Failed to generate private key and certificate!")
+        (>&2 echo "\n\nRefer to \"${LOG_FILE}\" for more detailed information")
+        return 1
+    }
 
     return 0
 }
@@ -94,17 +109,22 @@ stop_punica () {
     wait $1 || true
 }
 
-eval "${SCRIPTS_DIR}/format_style.sh --dry-run"
+echo "==> Checking code style..."
+eval "${SCRIPTS_DIR}/format_style.sh --dry-run" >> ${LOG_FILE} 2>&1
 
 if [ ! -x "${PROJECT_ROOT_DIR}/build/punica" ]
 then
-    echo "Punica binary not found! Exiting..."
+    echo "Punica binary not found!"
     exit 1
 fi
 
+if [ ! -f ${CERTIFICATE_SETTINGS_TEMPLATE} ]; then
+    eval "echo 'expiration_days 365' >> ${CERTIFICATE_SETTINGS_TEMPLATE}"
+fi
+
 echo "==> Generating security files..."
-generate_key_and_certificate ${TEST_PRIVATE_KEY} ${TEST_CERTIFICATE}
-generate_key_and_certificate ${OTHER_TEST_PRIVATE_KEY} ${OTHER_TEST_CERTIFICATE}
+generate_key_and_certificate ${TEST_PRIVATE_KEY} ${TEST_CERTIFICATE} ${CERTIFICATE_SETTINGS_TEMPLATE}
+generate_key_and_certificate ${OTHER_TEST_PRIVATE_KEY} ${OTHER_TEST_CERTIFICATE} ${CERTIFICATE_SETTINGS_TEMPLATE}
 
 echo "==> Starting punica(-s)..."
 REGULAR_PUNICA_PID=$(run_punica "regular")
@@ -123,4 +143,4 @@ echo "==> Stopping punica(-s)..."
 stop_punica $REGULAR_PUNICA_PID
 stop_punica $SECURE_PUNICA_PID
 
-exit $coverage_tests_status
+echo "Finished testing!"
