CI: add valgrind memory tests (#81)

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -21,6 +21,8 @@ set -e
 
 source "$(cd $(dirname "$0") && pwd -P)/.utils"
 
+TEST_TOOLS="valgrind gnutls-bin"
+
 CERTIFICATE_SETTINGS_TEMPLATE="${PROJECT_ROOT_DIR}/tests/rest/certificate_template.cfg"
 KEY_DIR="${PROJECT_ROOT_DIR}/tests/rest/keys"
 TEST_PRIVATE_KEY="${KEY_DIR}/private.key"
@@ -31,6 +33,10 @@ ECDSA_TEST_PRIVATE_KEY="${KEY_DIR}/ecdsa.key"
 ECDSA_TEST_CERTIFICATE="${KEY_DIR}/ecdsa.pem"
 
 CERTTOOL_BIN="certtool"
+
+SECURE_PUNICA_NAME="secure"
+REGULAR_PUNICA_NAME="regular"
+PLUGINS_PUNICA_NAME="plugins"
 
 build_test_plugins () {
     TEST_PLUGINS_DIR=$( cd "${PROJECT_ROOT_DIR}/tests/rest/plugins"; pwd )
@@ -124,10 +130,17 @@ get_path_level() {
 }
 
 run_punica () {
+    punica_log_file="/dev/null"
     initial_punica_arguments=""
     punica_command="${BUILD_DIR}/punica ${initial_punica_arguments}"
 
     if ! [ -z "$1" ]; then
+        if [ ! -d "${DEFAULT_LOG_DIR}" ]; then
+            eval "mkdir -p ${DEFAULT_LOG_DIR}"
+        fi
+        punica_log_file="${DEFAULT_LOG_DIR}/$1.log"
+        valgrind_log_file="${DEFAULT_LOG_DIR}/$1_valgrind.log"
+        punica_command="valgrind --leak-check=yes --log-file=${valgrind_log_file} ${punica_command}"
         strip_level="$(get_path_level ${PROJECT_ROOT_DIR})"
         coverage_prefix="GCOV_PREFIX_STRIP=${strip_level} GCOV_PREFIX=$1"
         punica_command="${coverage_prefix} ${punica_command}"
@@ -138,7 +151,7 @@ run_punica () {
         punica_command="${punica_command} ${punica_arguments}"
     fi
 
-    eval "${punica_command} > /dev/null &"
+    eval "${punica_command} > ${punica_log_file}  2>&1 &"
 
     echo $!
 }
@@ -166,7 +179,57 @@ stop_punica () {
     done
 }
 
+log_leak_check () {
+    echo "  - checking for leaks in $1" >> ${LOG_FILE} 2>&1
+
+    leak_summary=$(eval "tail -n 11 $1")
+
+    definite_leaks=$(echo "${leak_summary}" | awk 'NR == 2 {print $4; exit}')
+    indirect_leaks=$(echo "${leak_summary}" | awk 'NR == 3 {print $4; exit}')
+    possible_leaks=$(echo "${leak_summary}" | awk 'NR == 4 {print $4; exit}')
+    reachable_memory=$(echo "${leak_summary}" | awk 'NR == 5 {print $4; exit}')
+    suppressed=$(echo "${leak_summary}" | awk 'NR == 6 {print $3; exit}')
+
+    if [ "${definite_leaks}" != "0" ]\
+    || [ "${indirect_leaks}" != "0" ]\
+    || [ "${possible_leaks}" != "0" ];
+    then
+        return 1
+    fi
+
+    return 0
+}
+
+logs_leak_check () {
+    if [ -z "$1" ]; then
+        (>&2 echo "Invalid punica leak report log file!")
+        return 1
+    fi
+
+    logs_status=0
+    for log in $@; do
+        log_leak_check ${log}
+        log_status=$?
+        if [ ! $log_status -eq 0 ]; then
+            logs_status=1
+            echo "${leak_summary}" >> ${LOG_FILE} 2>&1
+        fi
+    done
+
+    if [ "${logs_status}" != "0" ]; then
+        (>&2 echo "Punica memory leaks found!")
+        (>&2 echo "Refer to \"${LOG_FILE}\" for more detailed information")
+    else
+        (echo "No Punica memory leaks found!")
+    fi
+
+    return $logs_status
+}
+
 sudo -v
+
+echo_and_log "==> Installing tools for testing..."
+install_software "${TEST_TOOLS}"
 
 echo_and_log "==> Checking code style..."
 eval "${SCRIPTS_DIR}/format_style.sh --dry-run" >> ${LOG_FILE} 2>&1
@@ -189,9 +252,9 @@ generate_key_and_certificate ${OTHER_TEST_PRIVATE_KEY} ${OTHER_TEST_CERTIFICATE}
 generate_key_and_certificate_ecdsa ${ECDSA_TEST_PRIVATE_KEY} ${ECDSA_TEST_CERTIFICATE}
 
 echo_and_log "==> Starting punica(-s)..."
-REGULAR_PUNICA_PID=$(run_punica "regular")
-SECURE_PUNICA_PID=$(run_punica "secure" "-c ${PROJECT_ROOT_DIR}/tests/rest/secure.cfg -d ${PROJECT_ROOT_DIR}/tests/rest/database.json")
-PLUGINS_PUNICA_PID=$(run_punica "plugins" "-c ./tests/rest/plugins.cfg")
+REGULAR_PUNICA_PID=$(run_punica "${REGULAR_PUNICA_NAME}")
+SECURE_PUNICA_PID=$(run_punica "${SECURE_PUNICA_NAME}" "-c ${PROJECT_ROOT_DIR}/tests/rest/secure.cfg -d ${PROJECT_ROOT_DIR}/tests/rest/database.json")
+PLUGINS_PUNICA_PID=$(run_punica "${PLUGINS_PUNICA_NAME}" "-c ./tests/rest/plugins.cfg")
 
 echo_and_log "==> Running coverage tests..."
 test_status=1
@@ -205,6 +268,16 @@ echo_and_log "==> Stopping punica(-s)..."
 stop_punica $REGULAR_PUNICA_PID
 stop_punica $SECURE_PUNICA_PID
 stop_punica $PLUGINS_PUNICA_PID
+
+if [ ${test_status} -eq 0 ];
+then
+    echo "==> Checking for leaks..."
+    logs_leak_check \
+        "${DEFAULT_LOG_DIR}/${REGULAR_PUNICA_NAME}_valgrind.log" \
+        "${DEFAULT_LOG_DIR}/${SECURE_PUNICA_NAME}_valgrind.log" \
+        "${DEFAULT_LOG_DIR}/${PLUGINS_PUNICA_NAME}_valgrind.log" \
+        || test_status=1
+fi
 
 echo_and_log "Finished testing!"
 
